Trash and archive
vermasavita/note-buk pull request #5
Opened 2022-05-17 16:18 UTC by vermasavita

###  What do you need to check?

- Delete Notes
- Archive Notes
- Delete from Archive
- Restore from Archive
- Delete Trash
- Restore from Trash
- 404 Error page
- Change favicon
- Refactor Code

Note: Ignore Filter commented code. I'll add that later

2022-05-17 16:26 UTC, sanjitsarkar approved these changes
Well written and readable code
Clean and Simple UI
Functionality is working as expected
Good to merge

2022-05-17 16:26 UTC, sanjitsarkar commented on src/pages/trash/Trash.jsx
> +          {trash.length !== 0 ? (
Suggestion: You can add trash.length>0 and it will be more meaningful.

2022-05-17 16:49 UTC, Naman-Saxena1 requested changes
Code looks fine, was not able to test functionality because preview is not working for me, maybe you can cross check that

2022-05-18 09:22 UTC, vermasavita commented
> Code looks fine, was not able to test functionality because preview is not working for me, maybe you can cross check that. Not able to create new note in preview

@Naman-Saxena1 Fixed that. Please check now and approve it.

2022-05-18 09:57 UTC, Naman-Saxena1 approved these changes

2022-05-18 14:26 UTC, merged